#!/bin/bash -e

D_VERSIONS=(
  20190619
  20181020
  20170516
  20160123
  20150417
  20140614
  20131224
  20121119
  20120807
  20120411
  20120228
  20120117
  20111031
)

declare -A SK_VERSIONS
SK_VERSIONS=(
  [20111017]=2.2.5
  [20110810]=2.2.4
  [20110715]=2.2.3
  [20110416]=2.1.1
  [20110403]=2.1
  [20110309]=2.0.6
  [20110209]=2.0.5
  [20101216]=2.0.4
  [20101208]=2.0.3
  [20101201]=2.0.2
  [20101128]=2.0.1
  [20101123]=2.0
  [20100723]=1.3
  [20100225]=1.1
  [20100212]=1.0.7
)

if (($# < 2)); then
  echo "Usage: $(basename $0) VERSION SKOOLKIT_VERSION"
  echo ""
  echo "  Attempts to build a specific version of the Contact Sam Cruise disassembly"
  echo "  using a specific version of SkoolKit."
  echo ""
  echo "  VERSION must be one of:"
  echo ""
  for v in ${D_VERSIONS[@]} ${!SK_VERSIONS[@]}; do
    echo "    $v"
  done | sort -r | column -c 80
  echo ""
  echo "  Environment variables:"
  echo "    CONTACTSAMCRUISE_HOME - root directory of the contactsamcruise project"
  echo "      (required for building version 20100723 and earlier)"
  echo "    DISASSEMBLY_ARCHIVE - directory containing disassembly release tarballs"
  echo "    SKOOLKIT_ARCHIVE - directory containing SkoolKit release tarballs"
  exit 1
fi

if [[ -z $SKOOLKIT_ARCHIVE ]]; then
    echo 'SKOOLKIT_ARCHIVE is not set; aborting'
    exit 1
fi
if [[ ! -d $SKOOLKIT_ARCHIVE ]]; then
    echo "SKOOLKIT_ARCHIVE=$SKOOLKIT_ARCHIVE: directory not found"
    exit 1
fi

if [[ -z $DISASSEMBLY_ARCHIVE ]]; then
    echo 'DISASSEMBLY_ARCHIVE is not set; aborting'
    exit 1
fi
if [[ ! -d $DISASSEMBLY_ARCHIVE ]]; then
    echo "DISASSEMBLY_ARCHIVE=$DISASSEMBLY_ARCHIVE: directory not found"
    exit 1
fi

D_VERSION=$1
SK_VERSION=$2

odir=csc-$D_VERSION-$SK_VERSION
rm -rf $odir
mkdir $odir
cd $odir

SK_DIR=skoolkit-$SK_VERSION
tar xf $SKOOLKIT_ARCHIVE/$SK_DIR.tar.*
SK_BUILD_DIR=${SK_DIR}-build
mv $SK_DIR $SK_BUILD_DIR

if (($D_VERSION >= 20111031)); then
  # Sources distributed separately from SkoolKit
  D_DIR=csc-disassembly-$D_VERSION
  tar xf $DISASSEMBLY_ARCHIVE/$D_DIR.tar.*
  cd $SK_BUILD_DIR
  find . -name '*.skool' -delete
  find . -name '*.ref' -delete
  cp -p ../$D_DIR/sources/*.skool .
  cp -p ../$D_DIR/sources/*.ref .
  cp -p ../$D_DIR/sources/*.css .
  cp -p ../$D_DIR/sources/*.js .
  [[ -d skoolkit ]] && [[ -d ../$D_DIR/skoolkit ]] && cp -p ../$D_DIR/skoolkit/*.py skoolkit
  find ../$D_DIR/sources -name '*.py' -exec cp -p {} . \;
else
  # Sources distributed with SkoolKit
  D_SK_VERSION=${SK_VERSIONS[$D_VERSION]}
  if [[ -z $D_SK_VERSION ]]; then
    echo "Disassembly version not recognised: $D_VERSION"
    exit 1
  fi
  D_SK_DIR=skoolkit-$D_SK_VERSION
  tar xf $SKOOLKIT_ARCHIVE/$D_SK_DIR.tar.*
  D_DIR=$D_SK_DIR-src
  mv $D_SK_DIR $D_DIR
  cd $SK_BUILD_DIR
  find . -name '*.skool' -delete
  find . -name '*.ref' -delete
  find . -name '*.ctl' -delete
  find ../$D_DIR -name 'csc*.skool' -exec cp -p {} . \;
  find ../$D_DIR -name 'csc*.ref' -exec cp -p {} . \;
  find ../$D_DIR -name 'contact_sam_cruise.ctl' -exec cp -p {} . \;
  if [[ -d skoolkit ]] && [[ -f ../$D_DIR/skoolkit/microsphere.py ]]; then
    cp -p ../$D_DIR/skoolkit/{microsphere,samcruise}.py skoolkit
  fi
fi

if [[ -f contact_sam_cruise.ctl ]]; then
  if [[ -z $CONTACTSAMCRUISE_HOME ]]; then
    echo 'CONTACTSAMCRUISE_HOME is not set; aborting'
    exit 1
  fi
  if [[ ! -d $CONTACTSAMCRUISE_HOME ]]; then
    echo "CONTACTSAMCRUISE_HOME=$CONTACTSAMCRUISE_HOME: directory not found"
    exit 1
  fi
  ./sna2skool.py -c contact_sam_cruise.ctl $CONTACTSAMCRUISE_HOME/build/contact_sam_cruise.z80 > csc.skool
fi

SK_VERSION_INT=$(echo $SK_VERSION | tr -d . )0
SK_VERSION_INT=${SK_VERSION_INT:0:3}

if (($SK_VERSION_INT >= 302)); then
  # Show timings in SkoolKit 3.0.2+
  OPTS=-t
fi

if (($SK_VERSION_INT >= 220)); then
  # SkoolKit 2.2+
  ./skool2html.py $OPTS -d ../html csc.skool
else
  # SkoolKit 1.0 - 2.1.2
  ./skool2html.py -f csc.skool ../html
fi
