#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $CONTACTSAMCRUISE_HOME ]]; then
  echo "Error: CONTACTSAMCRUISE_HOME not defined."
  exit 1
fi
if [[ ! -d $CONTACTSAMCRUISE_HOME ]]; then
  echo "Error: directory not found: $CONTACTSAMCRUISE_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

GAME=csc
GAMEDIR=contact_sam_cruise
GAMENAME="Contact Sam Cruise"
SKOOLFILES=$(echo {csc,load,save,start}.skool)
SRCFILES=$(echo COPYING samcruise.py {csc,bugs,changelog,data,facts,glossary,graphics,pages,pokes}.ref {csc,load,save,start}.skool {csc,dark,green,plum}.css tiles.js)
DHOME=$CONTACTSAMCRUISE_HOME
GHREPO=contactsamcruise
GHHTMLOPTS=""

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
